services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3003
      RUN_DB_GENERATE: "true"
      RUN_DB_MIGRATIONS: "true"
      RUN_DB_PUSH: "false"
    ports:
      - "3479:3003"
    volumes:
      - ./uploads:/app/uploads
